BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "stm32mp257f-custom"
BBFILE_PATTERN_stm32mp257f-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_stm32mp257f-custom = "10"

LAYERSERIES_COMPAT_stm32mp257f-custom = "scarthgap"
LAYERDEPENDS_stm32mp257f-custom = "core meta-st-stm32mp"
