# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# Remove ST's SDK tooling - since not working:
TOOLCHAIN_HOST_TASK:remove = "${ST_TOOLS_FOR_SDK}"
TOOLCHAIN_HOST_TASK:remove = "${ST_DEPENDENCIES_BUILD_FOR_SDK}"

GLIBC_GENERATE_LOCALES = "en_US.UTF-8"
IMAGE_LINGUAS = "en-us"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-yocto-stm32mp257f-dk"
BBFILE_PATTERN_meta-yocto-stm32mp257f-dk = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-yocto-stm32mp257f-dk = "7"

LAYERDEPENDS_meta-yocto-stm32mp257f-dk = "core"
LAYERSERIES_COMPAT_meta-yocto-stm32mp257f-dk = "scarthgap"

# INHERIT += "rm_work" - will remove the package work directory
#	once a package is built to save space on hard drive
INHERIT += "rm_work"

# The host does not delivers this packages
ASSUME_PROVIDED:remove="virtual/crypt-native"

# SSH server, select from: dropbear, openssh
IMAGE_INSTALL:append=" dropbear"
