# This is the config for Yocto stm32mp257f-dk board

# Define specific familly common machine name
# MACHINEOVERRIDES =. "stm32mp25-disco:"

require conf/machine/stm32mp25-disco.conf

MACHINE_FEATURES:remove = "splashscreen"
